version: '2.1'

services:
  node:
    container_name: nodeng
    image: scram_system
    build: .
    environment:
      NODE_ENV: production
    depends_on:
      - database
  database:
    container_name: db
    image: mongo
  nginx:
    container_name: nginx
    build: ./nginx
    image: reverseproxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
    ports:
      - 80:80
    depends_on: 
      - node
